require("dotenv").config();
const express = require("express");
const connectdb = require("./Db/db");
const cors = require("cors");

const productRoutes = require("./routes/productRoutes");

const userRoutes = require("./routes/userRoutes");
// const session = require("express-session");

const app = express();
app.use(cors());
app.use(express.json());

connectdb();
// app.use(
//   session({
//     secret: process.env.SECRET_KEY, //Use a strong secret in production
//     resave: true,
//     saveUninitialized: false,
//     cookie: { httpOnly: true, maxAge: 24 * 60 * 60 * 1000 }, // 1-day cookie lifespan
//   })
// );
app.use("/api/products", productRoutes);
app.use("/api/user", userRoutes);

// async function createElectronic() {
//   try {
//     await Electronics.create([
//       {
//         user: "675318b91deba0a48b54a266",
//         name: "Phone",
//         price: 639,
//         brand: "Sumsung Galaxy A15",
//         contInStock: 7,
//         rating: 1,
//         numReviews: 100,
//         description: "technology",
//         category: "Electronic",
//         image: "publicphone115.jpg",
//       },
//       {
//         user: "675318b91deba0a48b54a266",
//         name: "Phone",
//         price: 1159,
//         brand: "Sumsung Galaxy A25",
//         contInStock: 7,
//         rating: 2,
//         numReviews: 100,
//         description: "technology",
//         category: "Electronic",
//         image: "publicsum1.jpg",
//       },
//       {
//         user: "675318b91deba0a48b54a266",
//         name: "Phone",
//         price: 1159,
//         brand: "Sumsung Galaxy A25",
//         contInStock: 7,
//         rating: 2,
//         numReviews: 100,
//         description: "technology",
//         category: "Electronic",
//         image: "publicsum5.jpg",
//       },
//       {
//         user: "675318b91deba0a48b54a266",
//         name: "Phone",
//         price: 1159,
//         brand: "Sumsung Galaxy A25",
//         contInStock: 7,
//         rating: 2,
//         numReviews: 100,
//         description: "technology",
//         category: "Electronic",
//         image: "publicsum2.jpg",
//       },
//       {
//         user: "675318b91deba0a48b54a266",
//         name: "Phone",
//         price: 5699,
//         brand: "Sumsung Galaxy S24 Ultra",
//         contInStock: 8,
//         rating: 1,
//         numReviews: 100,
//         description: "technology",
//         category: "Electronic",
//         image: "publicphone114.jpg",
//       },
//       {
//         user: "675318b91deba0a48b54a266",
//         name: "Phone",
//         price: 4499,
//         brand: "Sumsung Galaxy S24 Plus",
//         contInStock: 6,
//         rating: 4,
//         numReviews: 100,
//         description: "technology",
//         category: "Electronic",
//         image: "publicphone114.jpg",
//       },
//       {
//         user: "675318b91deba0a48b54a266",
//         name: "Phone",
//         price: 4499,
//         brand: "Sumsung Galaxy S24 Plus",
//         contInStock: 6,
//         rating: 4,
//         numReviews: 100,
//         description: "technology",
//         category: "Electronic",
//         image: "publicphone115.jpg",
//       },
//       {
//         user: "675318b91deba0a48b54a266",
//         name: "Phone",
//         price: 7399,
//         brand: "iPhone 16 Pro",
//         contInStock: 4,
//         rating: 1,
//         numReviews: 100,
//         description: "technology",
//         category: "Electronic",
//         image: "publicphone1.jpg",
//       },

//       {
//         user: "675318b91deba0a48b54a266",
//         name: "Phone",
//         price: 7399,
//         brand: "iPhone 16 Pro",
//         contInStock: 4,
//         rating: 1,
//         numReviews: 100,
//         description: "technology",
//         category: "Electronic",
//         image: "phone 15.jpg",
//       },
//       {
//         user: "675318b91deba0a48b54a266",
//         name: "Phone",
//         price: 7300,
//         brand: "iPhone 16",
//         contInStock: 5,
//         rating: 4,
//         numReviews: 100,
//         description: "technology",
//         category: "Electronic",
//         image: "publicphone 4.jpg",
//       },
//       {
//         user: "675318b91deba0a48b54a266",
//         name: "Phone",
//         price: 5200,
//         brand: "iPhone 15",
//         contInStock: 1,
//         rating: 1,
//         numReviews: 100,
//         description: "technology",
//         category: "Electronic",
//         image: "publicphone 15.jpg",
//       },
//       {
//         user: "675318b91deba0a48b54a266",
//         name: "Phone",
//         price: 3600,
//         brand: "iPhone 14",
//         contInStock: 5,
//         rating: 2,
//         numReviews: 100,
//         description: "technology",
//         category: "Electronic",
//         image: "publicphone6.jpg",
//       },
//       {
//         user: "675318b91deba0a48b54a266",
//         name: "Phone",
//         price: 3600,
//         brand: "iPhone 14",
//         contInStock: 5,
//         rating: 2,
//         numReviews: 100,
//         description: "technology",
//         category: "Electronic",
//         image: "publicphone5.jpg",
//       },
//       {
//         user: "675318b91deba0a48b54a266",
//         name: "Phone",
//         price: 3600,
//         brand: "iPhone 14",
//         contInStock: 5,
//         rating: 2,
//         numReviews: 100,
//         description: "technology",
//         category: "Electronic",
//         image: "publicphone14.jpg",
//       },
//       {
//         user: "675318b91deba0a48b54a266",
//         name: "TV",
//         price: 575,
//         brand: "Toshiba",
//         contInStock: 5,
//         rating: 3,
//         numReviews: 100,
//         description: "technology",
//         category: "Electronic",
//         image: "public\tv1.jpg",
//       },
//       {
//         user: "675318b91deba0a48b54a266",
//         name: "TV",
//         price: 659,
//         brand: "biolux",
//         contInStock: 4,
//         rating: 6,
//         numReviews: 100,
//         description: "technology",
//         category: "Electronic",
//         image: "public\tv2.jpg",
//       },
//       {
//         user: "675318b91deba0a48b54a266",
//         name: "TV",
//         price: 679,
//         brand: "TCL",
//         contInStock: 5,
//         rating: 1,
//         numReviews: 100,
//         description: "technology",
//         category: "Electronic",
//         image: "public\tv3.jpg",
//       },
//       {
//         user: "675318b91deba0a48b54a266",
//         name: "TV",
//         price: 799,
//         brand: "Sumsung",
//         contInStock: 2,
//         rating: 1,
//         numReviews: 100,
//         description: "technology",
//         category: "Electronic",
//         image: "public\tv4.jpg",
//       },
//       {
//         user: "675318b91deba0a48b54a266",
//         name: "TV",
//         price: 799,
//         brand: "Sumsung",
//         contInStock: 2,
//         rating: 1,
//         numReviews: 100,
//         description: "technology",
//         category: "Electronic",
//         image: "public\tv9.jpg",
//       },
//       {
//         user: "675318b91deba0a48b54a266",
//         name: "TV",
//         price: 799,
//         brand: "Sumsung",
//         contInStock: 2,
//         rating: 1,
//         numReviews: 100,
//         description: "technology",
//         category: "Electronic",
//         image: "public\tv10.jpg",
//       },
//       {
//         user: "675318b91deba0a48b54a266",
//         name: "TV",
//         price: 799,
//         brand: "Sumsung",
//         contInStock: 2,
//         rating: 1,
//         numReviews: 100,
//         description: "technology",
//         category: "Electronic",
//         image: "public\tv9.jpg",
//       },
//       {
//         user: "675318b91deba0a48b54a266",
//         name: "Airpods",
//         price: 399,
//         brand: "JBL",
//         contInStock: 4,
//         rating: 3,
//         numReviews: 100,
//         description: "technology",
//         category: "Electronic",
//         image: "publicaipods11.jpg",
//       },
//       {
//         user: "675318b91deba0a48b54a266",
//         name: "Airpods",
//         price: 500,
//         brand: "Apple",
//         contInStock: 3,
//         rating: 1,
//         numReviews: 100,
//         description: "technology",
//         category: "Electronic",
//         image: "publicairpods1.jpg",
//       },
//       {
//         user: "675318b91deba0a48b54a266",
//         name: "Airpods",
//         price: 500,
//         brand: "Apple",
//         contInStock: 3,
//         rating: 1,
//         numReviews: 100,
//         description: "technology",
//         category: "Electronic",
//         image: "publicairpods2.jpg",
//       },
//       {
//         user: "675318b91deba0a48b54a266",
//         name: "Airpods",
//         price: 500,
//         brand: "Apple",
//         contInStock: 3,
//         rating: 1,
//         numReviews: 100,
//         description: "technology",
//         category: "Electronic",
//         image: "publicairpods3.jpg",
//       },
//       {
//         user: "675318b91deba0a48b54a266",
//         name: "Airpods",
//         price: 500,
//         brand: "Apple",
//         contInStock: 3,
//         rating: 1,
//         numReviews: 100,
//         description: "technology",
//         category: "Electronic",
//         image: "publicairpods1.jpg",
//       },
//       {
//         user: "675318b91deba0a48b54a266",
//         name: "Airpods",
//         price: 319,
//         brand: "JBL",
//         contInStock: 7,
//         rating: 2,
//         numReviews: 100,
//         description: "technology",
//         category: "Electronic",
//         image: "publicaipods12.jpg",
//       },
//       {
//         user: "675318b91deba0a48b54a266",
//         name: "Airpods",
//         price: 265,
//         brand: "Sumsung",
//         contInStock: 6,
//         rating: 2,
//         numReviews: 100,
//         description: "technology",
//         category: "Electronic",
//         image: "publicairpods8.jpg",
//       },
//       {
//         user: "675318b91deba0a48b54a266",
//         name: "Airpods",
//         price: 265,
//         brand: "Sumsung",
//         contInStock: 6,
//         rating: 2,
//         numReviews: 100,
//         description: "technology",
//         category: "Electronic",
//         image: "publicairpods9.jpg",
//       },
//       {
//         user: "675318b91deba0a48b54a266",
//         name: "Smart watch",
//         price: 2999,
//         brand: "Apple",
//         contInStock: 5,
//         rating: 2,
//         numReviews: 100,
//         description: "technology",
//         category: "Electronic",
//         image: "publicsmart watch.jpg",
//       },
//       {
//         user: "675318b91deba0a48b54a266",
//         name: "Smart watch",
//         price: 2899,
//         brand: "Apple",
//         contInStock: 4,
//         rating: 1,
//         numReviews: 100,
//         description: "technology",
//         category: "Electronic",
//         image: "publicsmartwatch4.jpg",
//       },
//       {
//         user: "675318b91deba0a48b54a266",
//         name: "Smart watch",
//         price: 2965,
//         brand: "Apple",
//         contInStock: 3,
//         rating: 2,
//         numReviews: 100,
//         description: "technology",
//         category: "Electronic",
//         image: "publicsmartwatch5.jpg",
//       },
//       {
//         user: "675318b91deba0a48b54a266",
//         name: "Smart watch",
//         price: 2555,
//         brand: "Apple",
//         contInStock: 2,
//         rating: 1,
//         numReviews: 100,
//         description: "technology",
//         category: "Electronic",
//         image: "publicsmartwatch3.jpg",
//       },
//       {
//         user: "675318b91deba0a48b54a266",
//         name: "Smart watch",
//         price: 2555,
//         brand: "Apple",
//         contInStock: 2,
//         rating: 1,
//         numReviews: 100,
//         description: "technology",
//         category: "Electronic",
//         image: "publicsmartwatch6.jpg",
//       },
//     ]);
//     console.log("success");
//   } catch (error) {
//     console.error(error.message);
//   }
// }
//createElectronic();

const port = process.env.PORT || 3000;
app.listen(port, () => {
  console.log(`Server running on port ${port}...`);
});
